parameters:
  artifactName: ''


steps:
- task: PublishPipelineArtifact@1
  displayName: Publish Artifacts to Artifactory
  inputs:
    path: $(Build.ArtifactStagingDirectory)
    artifactName: ${{ parameters.artifactName }}
    artifactType: pipeline
    parallel: true
    parallelCount: 10