 parameters:
  serviceConnection: ''
  subscription_id: ''
  tf_rg_name: ''
  tf_rg_location: ''
  tf_sa_name: ''
  tf_sa_sku: ''
  tf_sa_container_name: ''
  environment: ''
  DependsOn: ''
- name: artifactName
  type: string
  default: 'terraform_infra'
  values: 
  - 'terraform_infra'  


stages:
- stage: {{ parameters.environment }}_tf_init_plan
  displayName: Terraform Init and Plan
  ${{ if parameters.DependsOn }}:
    dependsOn: {{ parameters.DependsOn }}
  jobs:
  - template: ../jobs/tf_init_plan_job.yaml
    parameters:
      artifactName: ${{ parameters.artifactName }}_$(Build.BuildNumber)
      serviceConnection: ${{ parameters.serviceConnection }}
      subscription_id: ${{ parameters.subscription_id }}
      tf_rg_name: ${{ parameters.tf_rg_name }}
      tf_rg_location: ${{ parameters.tf_rg_location }}
      tf_sa_name: ${{ parameters.tf_sa_name }}
      tf_sa_sku: ${{ parameters.tf_sa_sku }}
      tf_sa_container_name: ${{ parameters.tf_sa_container_name }}
