parameters:
- name: env
  type: string
- name: DependsOn
  type: object
- name: artifactName
  type: string
  default: 'terraform_infra'
  values: 
  - 'terraform_infra'
- name: serviceConnection
  type: object



stages:
- stage: ${{ parameters.env }}_tf_init_plan
  displayName: Terraform Init and Plan
  variables:
  - group: ${{ parameters.env }}_tf_library
  # ${{ if parameters.DependsOn }}:
  #   dependsOn: ${{ parameters.DependsOn }}
  jobs:
  - template: ../jobs/tf_init_plan_job.yaml
    parameters:
      artifactName: ${{ parameters.artifactName }}_$(Build.BuildNumber)
      serviceConnection: ${{ parameters.serviceConnection }}
      subscription_id: $(subscription-id)
      tf_rg_name: $(tf-rg-name)
      tf_rg_location: $(tf-rg-location)
      tf_sa_name: $(tf-sa-name)
      tf_sa_sku: $(tf-sa-sku)
      tf_sa_container_name: $(tf-sa-container-name)
