parameters:
- name: environment
  type: string
- name: DependsOn
  type: string
- name: artifactName
  type: string
  default: 'terraform_infra'
  values: 
  - 'terraform_infra'

variables:
- group: ${{ parameters.environment }}_tf_library


stages:
- stage: ${{ parameters.environment }}_tf_init_plan
  displayName: Terraform Init and Plan
  ${{ if parameters.DependsOn }}:
    dependsOn: ${{ parameters.DependsOn }}
  jobs:
  - template: ../jobs/tf_init_plan_job.yaml
    parameters:
      artifactName: ${{ parameters.artifactName }}_$(Build.BuildNumber)
      serviceConnection: $(serviceConnection)
      subscription_id: $(subscription-id)
      tf_rg_name: $(tf-rg-name)
      tf_rg_location: $(tf-rg-location)
      tf_sa_name: $(tf-sa-name)
      tf_sa_sku: $(tf-sa-sku)
      tf_sa_container_name: $(tf-sa-container-name)
